server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - JwtAuthenticationFilter
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE
